# Social
spring:
  social:
    facebook:
      app-id: 1786413168344572
      app-secret: 26250b6f01efbb7674a935c4c7de468b
    twitter:
      app-id: mNEwtnt0584eEKNgprx1Xsk1W
      app-secret: OXTnEeAyEbgzeEbMHVagRsAGNAsUgUcT8iD9zNmobLvGSrH0LT
    linkedin:
      app-id: 7809an3x741o1c
      app-secret: GfZOXTQHP2JhEdSW
    vk:
      app-id: 5897956
      app-secret: efh7hv1pHE2CNuYc5jfz
      redirect-uri: http://localhost:8080/auth/vk
# SQL
  datasource:
    url: jdbc:mysql://localhost:3306/kursach2?characterEncoding=Cp1251
    username: root
    password: 14031984qwerty
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  thymeleaf:
    mode: LEGACYHTML5

  messages:
    basename: i18n/messages